### ISSUE TITLE
Adding the Light demo to Google Home

### ISSUE THREAD

**Issue by rvonzimr** [ducksauz/esp-matter-workshop#2]
Thought I'd write a comment here for testing on android via google home!

When pairing, there's no ability to continue with an unverified device. Instead, you'll need to create a developer project and a matter integration using the test vendor ID / product Id (0xfff2 and 0x8001 respectively).

[Creating a Developer Project](https://developers.home.google.com/matter/project/create)

[Pairing Restrictions](https://developers.home.google.com/matter/integration/pair#)

Point 4 being particularly relevant...

>- A Matter device can only be paired in the Google Home ecosystem in certain Vendor ID and device type scenarios.
>- A test VID cannot be used in a consumer device.
>- Your production VID must issued by the CSA. Google will validate you're the owner of that VID before you can use it in the Google Home Developer Console. Once that happens you'll be able to create integrations for that VID.
>- For development and field trial purposes, a project and integration with the corresponding VID and PID combination must be [created in the Developer Console](https://developers.home.google.com/matter/integration/create). The user commissioning the device must either be a member of the project or be included in the list of field trial users.
>- Consumer users can only use your product once it has been certified by the CSA.

Overall fairly restrictive, eventually got the light demo working though!

**Comment by ducksauz** [comment]
Thank you for noting this last year.
I finally added this (and credited you, of course) to the examples documentation, as I'm retreading this workshop at Teardown in Portland this weekend.
